---
- hosts: all
  become: yes
  become_user: root

  roles:
    - williamyeh.nodejs
  vars:
    nodejs_version: 4.0

  tasks:
    - name: Test connection
      ping: 

    - name: Install GCC
      yum: 
        pkg: gcc
        state: installed
        update_cache: yes

    - name: Download Redis Sources
      get_url:
        url: http://download.redis.io/releases/redis-stable.tar.gz
        dest: /root/redis.tar
      register: download_done

    - name: Extract Package
      unarchive: 
        src: /root/redis.tar
        dest: /root/
        copy: no
      when: download_done|changed

    - name: Make & Install
      make: chdir=/root/redis-stable/ target=install

    - name: Run Redis Server
      shell: redis-server --protected-mode no &

